# Generated by Django 3.1 on 2024-09-22 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_auto_20240922_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_slug', models.SlugField(max_length=200, unique=True)),
                ('product_description', models.TextField(blank=True, max_length=500)),
                ('product_price', models.IntegerField()),
                ('product_images', models.ImageField(upload_to='photos/products')),
                ('product_stock', models.IntegerField()),
                ('product_is_availabel', models.BooleanField(default=True)),
                ('product_created_date', models.DateTimeField(auto_now_add=True)),
                ('product_modifield_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
