# Generated by Django 3.1 on 2024-09-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('kids', 'Kids'), ('unisex', 'Unisex')], default='unisex', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='product_made_in',
            field=models.CharField(choices=[('VN', 'Vietnam'), ('CN', 'China'), ('ID', 'Indonesia'), ('TH', 'Thailand'), ('IN', 'India'), ('PH', 'Philippines'), ('PK', 'Pakistan'), ('TW', 'Taiwan'), ('MY', 'Malaysia'), ('BD', 'Bangladesh'), ('MX', 'Mexico'), ('IT', 'Italy'), ('BR', 'Brazil'), ('EG', 'Egypt'), ('TR', 'Turkey'), ('SK', 'South Korea'), ('US', 'United States')], default='VN', max_length=100),
        ),
    ]
