# Generated by Django 3.1 on 2024-09-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20240922_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_slug',
            new_name='productslug',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kid', 'Kid'), ('unisex', 'Unisex')], default='unisex', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_made_in',
            field=models.CharField(choices=[('VN', 'Vietnam'), ('CN', 'China'), ('ID', 'Indonesia'), ('TH', 'Thailand'), ('IN', 'India'), ('PH', 'Philippines'), ('PK', 'Pakistan'), ('TW', 'Taiwan'), ('MY', 'Malaysia'), ('BD', 'Bangladesh'), ('MX', 'Mexico'), ('IT', 'Italy'), ('BR', 'Brazil'), ('EG', 'Egypt'), ('TR', 'Turkey'), ('SK', 'South Korea'), ('US', 'United States'), ('CM', 'Cambodia')], default='VN', max_length=100),
        ),
    ]
