# Generated by Django 3.1 on 2024-09-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20240923_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productslug',
            new_name='slug',
        ),
    ]
