# Generated by Django 3.1 on 2024-09-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20240923_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_made_in',
            field=models.CharField(choices=[('Vietnam', 'Vietnam'), ('China', 'China'), ('Indonesia', 'Indonesia'), ('Thailand', 'Thailand'), ('India', 'India'), ('Philippines', 'Philippines'), ('Pakistan', 'Pakistan'), ('Taiwan', 'Taiwan'), ('Malaysia', 'Malaysia'), ('Bangladesh', 'Bangladesh'), ('Mexico', 'Mexico'), ('Italy', 'Italy'), ('Brazil', 'Brazil'), ('Egypt', 'Egypt'), ('Turkey', 'Turkey'), ('South Korea', 'South Korea'), ('United States', 'United States'), ('Cambodia', 'Cambodia')], default='VN', max_length=100),
        ),
    ]
