# Generated by Django 3.1 on 2024-09-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20240922_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_description',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
