# Generated by Django 3.1 on 2024-09-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20240922_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_slug',
            new_name='categoryslug',
        ),
    ]
