# Generated by Django 3.1 on 2024-09-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20240923_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryslug',
            new_name='slug',
        ),
    ]
